{
 "title": "MTG Infrastructure",
 "tags": [
  "mtg",
  "mtproto"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Активные подключения",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mtg_client_connections{job=\"mtg\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Трафик",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mtg_ip_packets_egress_bytes_total{job=\"mtg\"}[5m])",
     "legendFormat": "{{alias}} - Out"
    },
    {
     "expr": "rate(mtg_ip_packets_ingress_bytes_total{job=\"mtg\"}[5m])",
     "legendFormat": "{{alias}} - In"
    }
   ]
  },
  {
   "title": "Replay Attacks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mtg_replay_attacks{job=\"mtg\"}[15m])",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}